Client:
    type: entity
    table: client
    id:
        clientId:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: client_id
            generator:
                strategy: SEQUENCE
    fields:
        lastname:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
        firstname:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
        username:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
        civility:
            type: string
            nullable: true
            length: 30
            options:
                fixed: false
        email:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        phone:
            type: string
            nullable: true
            length: 30
            options:
                fixed: false
        address:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        city:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        state:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        zip:
            type: string
            nullable: true
            length: 10
            options:
                fixed: false
        password:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
    lifecycleCallbacks: {  }
